---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wele3795/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R /assets $DEPLOYPATH
    - /bin/cp -R /vendor $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp .cpanel.yml $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH